- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.GH_DEPLOY_TOKEN }}
    external_repository: YutangShi/YutangShi.github.io
    publish_branch: gh-pages
    publish_dir: ./public
